### ISSUE TITLE
The codes can't work well.

### ISSUE THREAD

**Issue by Mannix-D** [billhhh/ShaSpec#10] opened 2024-08-22 14:20 UTC
Hello, I have made the corresponding configurations according to your Markdown file, but the code still does not run. Could you provide runnable code?  There is an error as follows: 
![image](https://github.com/user-attachments/assets/69af172f-5146-4853-b696-f6e03c1ad86a)
The error codes are located as follows:
![image](https://github.com/user-attachments/assets/d384e053-f2bb-4736-9b4b-fd67f6378950)
Is there a need for modification?

**Comment by billhhh** [comment] 2024-08-24 15:58
Thank you for your interest about our project.
The code is runnable, according to others' reimplementation https://github.com/billhhh/ShaSpec/issues/1.

It may be caused by incompatible requirements. If the cudatoolkit issue there, conda virtualenv is a good start point. Please install all the requirements as in the requirements.txt files and try again.

**Comment by Mannix-D** [comment] 2024-08-26 02:48
Thank you for your reply, but my issue is different from that one.

**Comment by billhhh** [comment] 2024-08-26 09:25
I personally did not meet this issue before, and I suspect it caused by the requirements have not been fully installed.
So starting installing exactly the same requirements should be able to solve this issue.

https://github.com/billhhh/ShaSpec/blob/main/requirements.txt

**Comment by Mannix-D** [comment] 2024-08-27 01:20
Thank you for your advice. I have checked, and my setup meets the requirements. However, could you share which version of the random module you are using? It's possible that an update to the module has changed some functionality, rendering it incompatible with the current process. Upon reviewing the train.py file, I noticed that it only outputs the loss value and does not seem to include any code for calculating predictive accuracy. Could there be another part of the codebase where the accuracy is assessed?

**Comment by billhhh** [comment] 2024-09-22 16:02
Thank you for your questions. Currently, we release the code version on Brats but do not have plans for Audiovision-MNIST data, as Brats have much more influence on the field. The same question we answered here https://github.com/billhhh/ShaSpec/issues/9

**Comment by billhhh** [comment] 2024-09-23 18:48
Close the issue for now, if you have more questions, feel free to ask

**Closed as completed by billhhh** 2024-09-23 18:48 UTC
